
const BaseModel = require("./basemodel");
class Hospitalss extends BaseModel {
	static init(sequelize, Sequelize) {
		return super.init(
			{
				
				_id: { type: Sequelize.INTEGER, primaryKey: true , autoIncrement: true },
				created_date: {name: 'created_date', type:Sequelize.DATE},
				modified_date: {name: 'modified_date', type:Sequelize.DATE},
				hid: {name: 'hid', type:Sequelize.STRING},
				name: {name: 'name', type:Sequelize.STRING},
				payment_id: {name: 'payment_id', type:Sequelize.STRING},
				email: {name: 'email', type:Sequelize.STRING},
				address: {name: 'address', type:Sequelize.STRING},
				tagline: {name: 'tagline', type:Sequelize.STRING},
				city: {name: 'city', type:Sequelize.STRING},
				ownership: {name: 'ownership', type:Sequelize.STRING},
				type: {name: 'type', type:Sequelize.STRING},
				accreditation: {name: 'accreditation', type:Sequelize.STRING},
				registration_no: {name: 'registration_no', type:Sequelize.STRING},
				about: {name: 'about', type:Sequelize.STRING},
				state: {name: 'state', type:Sequelize.STRING},
				website: {name: 'website', type:Sequelize.STRING},
				latitude: {name: 'latitude', type:Sequelize.STRING},
				longitude: {name: 'longitude', type:Sequelize.STRING},
				insurance_accepted: {name: 'insurance_accepted', type:Sequelize.STRING},
				patients_per_day: {name: 'patients_per_day', type:Sequelize.STRING},
				emergency_service: {name: 'emergency_service', type:Sequelize.STRING},
				medical_tourisum_accepted: {name: 'medical_tourisum_accepted', type:Sequelize.STRING},
				password: {name: 'password', type:Sequelize.STRING},
				status: {name: 'status', type:Sequelize.STRING},
				url: {name: 'url', type:Sequelize.STRING},
				poc: {name: 'poc', type:Sequelize.STRING},
				rooms: {name: 'rooms', type:Sequelize.STRING},
				insurance: {name: 'insurance', type:Sequelize.STRING},
				token: {name: 'token', type:Sequelize.STRING},
				tpa: {name: 'tpa', type:Sequelize.STRING},
				bank_details: {name: 'bank_details', type:Sequelize.STRING},
				hospital_logo: {name: 'hospital_logo', type:Sequelize.STRING},
				district: {name: 'district', type:Sequelize.STRING},
				avg_patients: {name: 'avg_patients', type:Sequelize.STRING},
				tv_installed: {name: 'tv_installed', type:Sequelize.STRING},
				specialties: {name: 'specialties', type:Sequelize.STRING},
				facilities: {name: 'facilities', type:Sequelize.STRING},
				ayush: {name: 'ayush', type:Sequelize.STRING},
				contact: {name: 'contact', type:Sequelize.STRING},
				pincode: {name: 'pincode', type:Sequelize.STRING},
				icu_beds: {name: 'icu_beds', type:Sequelize.STRING},
				_v: {name: '_v', type:Sequelize.STRING},
				branches: {name: 'branches', type:Sequelize.STRING},
				beds: {name: 'beds', type:Sequelize.STRING},
				staff: {name: 'staff', type:Sequelize.STRING},
				ventilator_beds: {name: 'ventilator_beds', type:Sequelize.STRING},
				doctors: {name: 'doctors', type:Sequelize.STRING},
				rohini_id: {name: 'rohini_id', type:Sequelize.STRING},
				logo: {name: 'logo', type:Sequelize.STRING},
				test: {name: 'test', type:Sequelize.STRING},
				test1: {name: 'test1', type:Sequelize.STRING}
			}, 
			{ 
				sequelize,
				schema: "public", 
				tableName: "hospitalss",
				modelName: "hospitalss",
			}
		);
	}
	
	static listFields() {
		let sequelize = this.sequelize;
		return [
			'_id', 
			'created_date', 
			'modified_date', 
			'hid', 
			'name', 
			'payment_id', 
			'email', 
			'address', 
			'tagline', 
			'city', 
			'ownership', 
			'type', 
			'accreditation', 
			'registration_no', 
			'about', 
			'state', 
			'website', 
			'latitude', 
			'longitude', 
			'insurance_accepted', 
			'patients_per_day', 
			'emergency_service', 
			'medical_tourisum_accepted', 
			'status', 
			'url', 
			'poc', 
			'rooms', 
			'insurance', 
			'token', 
			'tpa', 
			'bank_details', 
			'hospital_logo', 
			'district', 
			'avg_patients', 
			'tv_installed', 
			'specialties', 
			'facilities', 
			'ayush', 
			'contact', 
			'pincode', 
			'icu_beds', 
			'_v', 
			'branches', 
			'beds', 
			'staff', 
			'ventilator_beds', 
			'doctors', 
			'rohini_id', 
			'logo', 
			'test', 
			'test1'
		];
	}

	static exportListFields() {
		let sequelize = this.sequelize;
		return [
			'_id', 
			'created_date', 
			'modified_date', 
			'hid', 
			'name', 
			'payment_id', 
			'email', 
			'address', 
			'tagline', 
			'city', 
			'ownership', 
			'type', 
			'accreditation', 
			'registration_no', 
			'about', 
			'state', 
			'website', 
			'latitude', 
			'longitude', 
			'insurance_accepted', 
			'patients_per_day', 
			'emergency_service', 
			'medical_tourisum_accepted', 
			'status', 
			'url', 
			'poc', 
			'rooms', 
			'insurance', 
			'token', 
			'tpa', 
			'bank_details', 
			'hospital_logo', 
			'district', 
			'avg_patients', 
			'tv_installed', 
			'specialties', 
			'facilities', 
			'ayush', 
			'contact', 
			'pincode', 
			'icu_beds', 
			'_v', 
			'branches', 
			'beds', 
			'staff', 
			'ventilator_beds', 
			'doctors', 
			'rohini_id', 
			'logo', 
			'test', 
			'test1'
		];
	}

	static viewFields() {
		let sequelize = this.sequelize;
		return [
			'_id', 
			'created_date', 
			'modified_date', 
			'hid', 
			'name', 
			'payment_id', 
			'email', 
			'address', 
			'tagline', 
			'city', 
			'ownership', 
			'type', 
			'accreditation', 
			'registration_no', 
			'about', 
			'state', 
			'website', 
			'latitude', 
			'longitude', 
			'insurance_accepted', 
			'patients_per_day', 
			'emergency_service', 
			'medical_tourisum_accepted', 
			'status', 
			'url', 
			'poc', 
			'rooms', 
			'insurance', 
			'token', 
			'tpa', 
			'bank_details', 
			'hospital_logo', 
			'district', 
			'avg_patients', 
			'tv_installed', 
			'specialties', 
			'facilities', 
			'ayush', 
			'contact', 
			'pincode', 
			'icu_beds', 
			'_v', 
			'branches', 
			'beds', 
			'staff', 
			'ventilator_beds', 
			'doctors', 
			'rohini_id', 
			'logo', 
			'test', 
			'test1'
		];
	}

	static exportViewFields() {
		let sequelize = this.sequelize;
		return [
			'_id', 
			'created_date', 
			'modified_date', 
			'hid', 
			'name', 
			'payment_id', 
			'email', 
			'address', 
			'tagline', 
			'city', 
			'ownership', 
			'type', 
			'accreditation', 
			'registration_no', 
			'about', 
			'state', 
			'website', 
			'latitude', 
			'longitude', 
			'insurance_accepted', 
			'patients_per_day', 
			'emergency_service', 
			'medical_tourisum_accepted', 
			'status', 
			'url', 
			'poc', 
			'rooms', 
			'insurance', 
			'token', 
			'tpa', 
			'bank_details', 
			'hospital_logo', 
			'district', 
			'avg_patients', 
			'tv_installed', 
			'specialties', 
			'facilities', 
			'ayush', 
			'contact', 
			'pincode', 
			'icu_beds', 
			'_v', 
			'branches', 
			'beds', 
			'staff', 
			'ventilator_beds', 
			'doctors', 
			'rohini_id', 
			'logo', 
			'test', 
			'test1'
		];
	}

	static editFields() {
		let sequelize = this.sequelize;
		return [
			'_id', 
			'created_date', 
			'modified_date', 
			'hid', 
			'name', 
			'payment_id', 
			'email', 
			'address', 
			'tagline', 
			'city', 
			'ownership', 
			'type', 
			'accreditation', 
			'registration_no', 
			'about', 
			'state', 
			'website', 
			'latitude', 
			'longitude', 
			'insurance_accepted', 
			'patients_per_day', 
			'emergency_service', 
			'medical_tourisum_accepted', 
			'status', 
			'url', 
			'poc', 
			'rooms', 
			'insurance', 
			'token', 
			'tpa', 
			'bank_details', 
			'hospital_logo', 
			'district', 
			'avg_patients', 
			'tv_installed', 
			'specialties', 
			'facilities', 
			'ayush', 
			'contact', 
			'pincode', 
			'icu_beds', 
			'_v', 
			'branches', 
			'beds', 
			'staff', 
			'ventilator_beds', 
			'doctors', 
			'rohini_id', 
			'logo', 
			'test', 
			'test1'
		];
	}

	
	static searchFields(){
		let sequelize = this.sequelize;
		return [
			sequelize.literal("hid iLIKE :search"), 
			sequelize.literal("name iLIKE :search"), 
			sequelize.literal("email iLIKE :search"), 
			sequelize.literal("address iLIKE :search"), 
			sequelize.literal("tagline iLIKE :search"), 
			sequelize.literal("city iLIKE :search"), 
			sequelize.literal("ownership iLIKE :search"), 
			sequelize.literal("type iLIKE :search"), 
			sequelize.literal("accreditation iLIKE :search"), 
			sequelize.literal("registration_no iLIKE :search"), 
			sequelize.literal("about iLIKE :search"), 
			sequelize.literal("state iLIKE :search"), 
			sequelize.literal("website iLIKE :search"), 
			sequelize.literal("latitude iLIKE :search"), 
			sequelize.literal("longitude iLIKE :search"), 
			sequelize.literal("insurance_accepted iLIKE :search"), 
			sequelize.literal("patients_per_day iLIKE :search"), 
			sequelize.literal("emergency_service iLIKE :search"), 
			sequelize.literal("medical_tourisum_accepted iLIKE :search"), 
			sequelize.literal("password iLIKE :search"), 
			sequelize.literal("status iLIKE :search"), 
			sequelize.literal("url iLIKE :search"), 
			sequelize.literal("hospital_logo iLIKE :search"), 
			sequelize.literal("district iLIKE :search"), 
			sequelize.literal("avg_patients iLIKE :search"), 
			sequelize.literal("tv_installed iLIKE :search"), 
			sequelize.literal("contact iLIKE :search"), 
			sequelize.literal("pincode iLIKE :search"), 
			sequelize.literal("icu_beds iLIKE :search"), 
			sequelize.literal("_v iLIKE :search"), 
			sequelize.literal("branches iLIKE :search"), 
			sequelize.literal("beds iLIKE :search"), 
			sequelize.literal("staff iLIKE :search"), 
			sequelize.literal("ventilator_beds iLIKE :search"), 
			sequelize.literal("doctors iLIKE :search"), 
			sequelize.literal("logo iLIKE :search"),
		];
	}

	
	
}
module.exports = Hospitalss;
