
const BaseModel = require("./basemodel");
class Testing extends BaseModel {
	static init(sequelize, Sequelize) {
		return super.init(
			{
				
				_id: { type: Sequelize.INTEGER, primaryKey: true , autoIncrement: true },
				specialities: {name: 'specialities', type:Sequelize.STRING},
				facilities: {name: 'facilities', type:Sequelize.STRING},
				ayush: {name: 'ayush', type:Sequelize.STRING},
				name: {name: 'name', type:Sequelize.STRING},
				payment_id: {name: 'payment_id', type:Sequelize.STRING},
				contact: {name: 'contact', type:Sequelize.DECIMAL},
				email: {name: 'email', type:Sequelize.STRING},
				address: {name: 'address', type:Sequelize.STRING},
				tagline: {name: 'tagline', type:Sequelize.STRING},
				pincode: {name: 'pincode', type:Sequelize.DECIMAL},
				city: {name: 'city', type:Sequelize.STRING},
				ownership: {name: 'ownership', type:Sequelize.STRING},
				type: {name: 'type', type:Sequelize.STRING},
				accreditation: {name: 'accreditation', type:Sequelize.STRING},
				registration_no: {name: 'registration_no', type:Sequelize.STRING},
				about: {name: 'about', type:Sequelize.STRING},
				state: {name: 'state', type:Sequelize.STRING},
				website: {name: 'website', type:Sequelize.STRING},
				latitude: {name: 'latitude', type:Sequelize.STRING},
				longitude: {name: 'longitude', type:Sequelize.STRING},
				insurance_accepted: {name: 'insurance_accepted', type:Sequelize.STRING},
				branches: {name: 'branches', type:Sequelize.DECIMAL},
				bed: {name: 'bed', type:Sequelize.DECIMAL},
				doctors: {name: 'doctors', type:Sequelize.STRING},
				staff: {name: 'staff', type:Sequelize.DECIMAL},
				patients_per_day: {name: 'patients_per_day', type:Sequelize.DECIMAL},
				emergency_service: {name: 'emergency_service', type:Sequelize.STRING},
				icu_beds: {name: 'icu_beds', type:Sequelize.DECIMAL},
				ventilator_beds: {name: 'ventilator_beds', type:Sequelize.DECIMAL},
				medical_tourism: {name: 'medical_tourism', type:Sequelize.STRING},
				password: {name: 'password', type:Sequelize.STRING},
				status: {name: 'status', type:Sequelize.STRING},
				hid: {name: 'HID', type:Sequelize.STRING},
				url: {name: 'url', type:Sequelize.STRING},
				created_date: {name: 'created_date', type:Sequelize.DATEONLY},
				modified_date: {name: 'modified_date', type:Sequelize.DATEONLY},
				logo: {name: 'logo', type:Sequelize.STRING},
				poc: {name: 'poc', type:Sequelize.STRING},
				rooms: {name: 'rooms', type:Sequelize.STRING},
				createdat: {name: 'createdAt', type:Sequelize.DATEONLY},
				insurance: {name: 'insurance', type:Sequelize.STRING},
				tokens: {name: 'tokens', type:Sequelize.STRING},
				tpa: {name: 'tpa', type:Sequelize.STRING},
				updatedat: {name: 'updatedAt', type:Sequelize.DATEONLY},
				bank_details: {name: 'bank_details', type:Sequelize.STRING},
				hospitallogo: {name: 'hospitalLogo', type:Sequelize.STRING},
				district: {name: 'district', type:Sequelize.STRING},
				avg_patients: {name: 'avg_patients', type:Sequelize.DECIMAL},
				tv_installed: {name: 'tv_installed', type:Sequelize.STRING},
				test: {name: 'test', type:Sequelize.STRING}
			}, 
			{ 
				sequelize,
				schema: "public", 
				tableName: "testing",
				modelName: "testing",
			}
		);
	}
	
	static listFields() {
		let sequelize = this.sequelize;
		return [
			'_id', 
			'specialities', 
			'facilities', 
			'ayush', 
			'name', 
			'payment_id', 
			'contact', 
			'email', 
			'address', 
			'tagline', 
			'pincode', 
			'city', 
			'ownership', 
			'type', 
			'accreditation', 
			'registration_no', 
			'about', 
			'state', 
			'website', 
			'latitude', 
			'longitude', 
			'insurance_accepted', 
			'branches', 
			'bed', 
			'doctors', 
			'staff', 
			'patients_per_day', 
			'emergency_service', 
			'icu_beds', 
			'ventilator_beds', 
			'medical_tourism', 
			'status', 
			sequelize.literal('HID AS hid'), 
			'url', 
			'created_date', 
			'modified_date', 
			'logo', 
			'poc', 
			'rooms', 
			sequelize.literal('createdAt AS createdat'), 
			'insurance', 
			'tokens', 
			'tpa', 
			sequelize.literal('updatedAt AS updatedat'), 
			'bank_details', 
			sequelize.literal('hospitalLogo AS hospitallogo'), 
			'district', 
			'avg_patients', 
			'tv_installed', 
			'test'
		];
	}

	static exportListFields() {
		let sequelize = this.sequelize;
		return [
			'_id', 
			'specialities', 
			'facilities', 
			'ayush', 
			'name', 
			'payment_id', 
			'contact', 
			'email', 
			'address', 
			'tagline', 
			'pincode', 
			'city', 
			'ownership', 
			'type', 
			'accreditation', 
			'registration_no', 
			'about', 
			'state', 
			'website', 
			'latitude', 
			'longitude', 
			'insurance_accepted', 
			'branches', 
			'bed', 
			'doctors', 
			'staff', 
			'patients_per_day', 
			'emergency_service', 
			'icu_beds', 
			'ventilator_beds', 
			'medical_tourism', 
			'status', 
			sequelize.literal('HID AS hid'), 
			'url', 
			'created_date', 
			'modified_date', 
			'logo', 
			'poc', 
			'rooms', 
			sequelize.literal('createdAt AS createdat'), 
			'insurance', 
			'tokens', 
			'tpa', 
			sequelize.literal('updatedAt AS updatedat'), 
			'bank_details', 
			sequelize.literal('hospitalLogo AS hospitallogo'), 
			'district', 
			'avg_patients', 
			'tv_installed', 
			'test'
		];
	}

	static viewFields() {
		let sequelize = this.sequelize;
		return [
			'_id', 
			'specialities', 
			'facilities', 
			'ayush', 
			'name', 
			'payment_id', 
			'contact', 
			'email', 
			'address', 
			'tagline', 
			'pincode', 
			'city', 
			'ownership', 
			'type', 
			'accreditation', 
			'registration_no', 
			'about', 
			'state', 
			'website', 
			'latitude', 
			'longitude', 
			'insurance_accepted', 
			'branches', 
			'bed', 
			'doctors', 
			'staff', 
			'patients_per_day', 
			'emergency_service', 
			'icu_beds', 
			'ventilator_beds', 
			'medical_tourism', 
			'status', 
			sequelize.literal('HID AS hid'), 
			'url', 
			'created_date', 
			'modified_date', 
			'logo', 
			'poc', 
			'rooms', 
			sequelize.literal('createdAt AS createdat'), 
			'insurance', 
			'tokens', 
			'tpa', 
			sequelize.literal('updatedAt AS updatedat'), 
			'bank_details', 
			sequelize.literal('hospitalLogo AS hospitallogo'), 
			'district', 
			'avg_patients', 
			'tv_installed', 
			'test'
		];
	}

	static exportViewFields() {
		let sequelize = this.sequelize;
		return [
			'_id', 
			'specialities', 
			'facilities', 
			'ayush', 
			'name', 
			'payment_id', 
			'contact', 
			'email', 
			'address', 
			'tagline', 
			'pincode', 
			'city', 
			'ownership', 
			'type', 
			'accreditation', 
			'registration_no', 
			'about', 
			'state', 
			'website', 
			'latitude', 
			'longitude', 
			'insurance_accepted', 
			'branches', 
			'bed', 
			'doctors', 
			'staff', 
			'patients_per_day', 
			'emergency_service', 
			'icu_beds', 
			'ventilator_beds', 
			'medical_tourism', 
			'status', 
			sequelize.literal('HID AS hid'), 
			'url', 
			'created_date', 
			'modified_date', 
			'logo', 
			'poc', 
			'rooms', 
			sequelize.literal('createdAt AS createdat'), 
			'insurance', 
			'tokens', 
			'tpa', 
			sequelize.literal('updatedAt AS updatedat'), 
			'bank_details', 
			sequelize.literal('hospitalLogo AS hospitallogo'), 
			'district', 
			'avg_patients', 
			'tv_installed', 
			'test'
		];
	}

	static editFields() {
		let sequelize = this.sequelize;
		return [
			'_id', 
			'specialities', 
			'facilities', 
			'ayush', 
			'name', 
			'payment_id', 
			'contact', 
			'email', 
			'address', 
			'tagline', 
			'pincode', 
			'city', 
			'ownership', 
			'type', 
			'accreditation', 
			'registration_no', 
			'about', 
			'state', 
			'website', 
			'latitude', 
			'longitude', 
			'insurance_accepted', 
			'branches', 
			'bed', 
			'doctors', 
			'staff', 
			'patients_per_day', 
			'emergency_service', 
			'icu_beds', 
			'ventilator_beds', 
			'medical_tourism', 
			'status', 
			sequelize.literal('HID AS hid'), 
			'url', 
			'created_date', 
			'modified_date', 
			'logo', 
			'poc', 
			'rooms', 
			sequelize.literal('createdAt AS createdat'), 
			'insurance', 
			'tokens', 
			'tpa', 
			sequelize.literal('updatedAt AS updatedat'), 
			'bank_details', 
			sequelize.literal('hospitalLogo AS hospitallogo'), 
			'district', 
			'avg_patients', 
			'tv_installed', 
			'test'
		];
	}

	
	static searchFields(){
		let sequelize = this.sequelize;
		return [
			sequelize.literal("name iLIKE :search"), 
			sequelize.literal("email iLIKE :search"), 
			sequelize.literal("address iLIKE :search"), 
			sequelize.literal("tagline iLIKE :search"), 
			sequelize.literal("city iLIKE :search"), 
			sequelize.literal("ownership iLIKE :search"), 
			sequelize.literal("type iLIKE :search"), 
			sequelize.literal("accreditation iLIKE :search"), 
			sequelize.literal("registration_no iLIKE :search"), 
			sequelize.literal("about iLIKE :search"), 
			sequelize.literal("state iLIKE :search"), 
			sequelize.literal("website iLIKE :search"), 
			sequelize.literal("latitude iLIKE :search"), 
			sequelize.literal("longitude iLIKE :search"), 
			sequelize.literal("insurance_accepted iLIKE :search"), 
			sequelize.literal("emergency_service iLIKE :search"), 
			sequelize.literal("medical_tourism iLIKE :search"), 
			sequelize.literal("password iLIKE :search"), 
			sequelize.literal("status iLIKE :search"), 
			sequelize.literal("HID iLIKE :search"), 
			sequelize.literal("url iLIKE :search"), 
			sequelize.literal("logo iLIKE :search"), 
			sequelize.literal("hospitalLogo iLIKE :search"), 
			sequelize.literal("district iLIKE :search"), 
			sequelize.literal("tv_installed iLIKE :search"),
		];
	}

	
	
}
module.exports = Testing;
